OLED_ENABLE = no
# OLED_DRIVER = SSD1306      # Enables the use of OLED displays
ENCODER_ENABLE = yes       # Enables the use of one or more encoders
RGB_MATRIX_ENABLE = no     # Disable keyboard RGB matrix, as it is enabled by default on rev3
RGBLIGHT_ENABLE = yes      # Enable keyboard RGB underglow
CONVERT_TO = liatris
COMMAND_ENABLE = yes
CONSOLE_ENABLE = yes
CAPS_WORD_ENABLE = yes
DYNAMIC_TAPPING_TERM_ENABLE = yes
TAP_DANCE_ENABLE = yes
COMBO_ENABLE = yes
AUTO_SHIFT_ENABLE = yes
